SELECT COUNT(*) AS Total_Flights
FROM flights;

SELECT COUNT(*) AS Cancelled_Flights
FROM flights
WHERE CANCELLED= 1;

SELECT COUNT(*) AS Diverted_Flights
FROM flights
WHERE DIVERTED= 1;

SELECT ROUND(AVG(ARRIVAL_DELAY),2) AS Avg_Arrival_Delay
FROM flights;

SELECT ROUND(AVG(DEPARTURE_DELAY),2) AS Avg_Departure_Delay
FROM flights;

SELECT
a.AIRLINE,
COUNT(*) AS Total_Flights
FROM flights f
JOIN airlines a
ON f.AIRLINE = a.IATA_CODE
GROUP BY a.AIRLINE
ORDER BY Total_Flights DESC;

SELECT
a.AIRLINE,
ROUND(AVG(f.ARRIVAL_DELAY),2) AS Avg_Arrival_Delay
FROM flights f
JOIN airlines a
ON f.AIRLINE = a.IATA_CODE
GROUP BY a.AIRLINE
ORDER BY Avg_Arrival_Delay DESC;

SELECT
a.AIRLINE,
ROUND(AVG(f.DEPARTURE_DELAY),2) AS Avg_Departure_Delay
FROM flights f
JOIN airlines a
ON f.AIRLINE = a.IATA_CODE
GROUP BY a.AIRLINE
ORDER BY Avg_Departure_Delay DESC;

SELECT
ORIGIN_AIRPORT,
COUNT(*) AS Total_Flights
FROM flights
GROUP BY ORIGIN_AIRPORT
ORDER BY Total_Flights DESC
LIMIT 20;

SELECT
ORIGIN_AIRPORT,
ROUND(AVG(DEPARTURE_DELAY),2) AS Avg_Delay
FROM flights
GROUP BY ORIGIN_AIRPORT
ORDER BY Avg_Delay DESC
LIMIT 20;

SELECT
DAY_OF_WEEK,
ROUND(AVG(DEPARTURE_DELAY),2) AS Avg_Delay
FROM flights
GROUP BY DAY_OF_WEEK
ORDER BY DAY_OF_WEEK;

SELECT
ORIGIN_AIRPORT,
DESTINATION_AIRPORT,
DISTANCE
FROM flights
ORDER BY DISTANCE DESC
LIMIT 20;

SELECT
ROUND(AVG(CAST(AIR_SYSTEM_DELAY AS DECIMAL(10,2))),2),
ROUND(AVG(CAST(SECURITY_DELAY AS DECIMAL(10,2))),2),
ROUND(AVG(CAST(AIRLINE_DELAY AS DECIMAL(10,2))),2),
ROUND(AVG(CAST(LATE_AIRCRAFT_DELAY AS DECIMAL(10,2))),2),
ROUND(AVG(CAST(WEATHER_DELAY AS DECIMAL(10,2))),2)
FROM flights;